title: Dheer Patel
description: Master's student in Robotics, Cognition, Intelligence at TUM
url: "https://dheerpatel.github.io"
baseurl: ""

# Personal info
name: Dheer Patel
email: dheer.patel@tum.de
phone: "+49 163 7154014"
linkedin: "https://www.linkedin.com/in/DheerPatel"
location: "Munich, Germany"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
